set(file_path "/etc/os-release")

if(EXISTS "${file_path}")
    file(STRINGS "${file_path}" data_list REGEX "^(ID|VARIANT_ID|VERSION_ID)=")
    foreach(line ${data_list})
        if("${line}" MATCHES "^(ID)=(.*)$")
            set(OS_ID "${CMAKE_MATCH_2}")
        elseif("${line}" MATCHES "^(VARIANT_ID)=(.*)$")
            set(OS_VARIANT_ID "${CMAKE_MATCH_2}")
        elseif("${line}" MATCHES "^(VERSION_ID)=(.*)$")
            set(OS_VERSION_ID "${CMAKE_MATCH_2}")
        endif("${line}" MATCHES "^(ID)=(.*)$")
    endforeach(line)
endif(EXISTS "${file_path}")
