file(STRINGS "VERSION" SOFTWARE_VERSION)

message(STATUS "Software version: ${SOFTWARE_VERSION}")

string(REPLACE "." ";" VERSION_LIST ${SOFTWARE_VERSION})
list(GET VERSION_LIST 0 SOFTWARE_VERSION_MAJOR)
list(GET VERSION_LIST 1 SOFTWARE_VERSION_MINOR)
list(GET VERSION_LIST 2 SOFTWARE_VERSION_PATCH)

set_target_properties(${PROJECT_NAME}
    PROPERTIES
        SOVERSION ${SOFTWARE_VERSION_MAJOR}
)
